var emplyeesData = [
     { "empId": 101, "name": "Abhay", "Salary": 10000, "DOJ": "2014-07-07" },
     { "empId": 102, "name": "Amruta", "Salary": 15000, "DOJ": "2014-07-07" },
     { "empId": 103, "name": "Ajay", "Salary": 30000, "DOJ": "2014-07-07" },
     { "empId": 104, "name": "Alok", "Salary": 20000, "DOJ": "2014-07-07" },
     { "empId": 105, "name": "Abhishek", "Salary": 20000, "DOJ": "2014-07-07" },
     { "empId": 106, "name": "AmitB", "Salary": 20000, "DOJ": "2014-07-07" },
     { "empId": 107, "name": "Dnyanesh", "Salary": 20000, "DOJ": "2014-07-07" },
     { "empId": 108, "name": "Kiran", "Salary": 20000, "DOJ": "2014-07-07" },
     { "empId": 109, "name": "Dharmin", "Salary": 20000, "DOJ": "2014-07-07" },
     { "empId": 110, "name": "Tushar", "Salary": 20000, "DOJ": "2014-07-07" },
];

var LoginData = [
     { "UserID": "Admin", "Password": "Abcd@123" },
     { "UserID": "Abhay", "Password": "Abcd@123" },
   
];