var employeesData = [
     { "empId": 101, "name": "Abhay", "Salary": 10000, "DOJ": "2014-07-07","gender":"Male","Role" : "Architect" },
     { "empId": 102, "name": "Amruta", "Salary": 15000, "DOJ": "2014-07-07", "gender": "Female", "Role": "Test Lead" },
     { "empId": 103, "name": "Ajay", "Salary": 30000, "DOJ": "2014-07-07", "gender": "Male", "Role": "Manager" },
     { "empId": 104, "name": "Alok", "Salary": 20000, "DOJ": "2014-07-07", "gender": "Male", "Role": "Developer" },
     { "empId": 105, "name": "Abhishek", "Salary": 20000, "DOJ": "2014-07-07", "gender": "Male", "Role": "Developer" },
     { "empId": 106, "name": "AmitB", "Salary": 20000, "DOJ": "2014-07-07", "gender": "Male", "Role": "QA" },
     { "empId": 107, "name": "Dnyanesh", "Salary": 20000, "DOJ": "2014-07-07", "gender": "Male", "Role": "Developer" },
     { "empId": 108, "name": "Kiran", "Salary": 20000, "DOJ": "2014-07-07", "gender": "Male", "Role": "Developer" },
     { "empId": 109, "name": "Dharmin", "Salary": 20000, "DOJ": "2014-07-07", "gender": "Male", "Role": "Developer" },
     { "empId": 110, "name": "Tushar", "Salary": 20000, "DOJ": "2014-07-07", "gender": "Male", "Role": "Developer" },
];

var LoginData = [
     { "UserID": "Admin", "Password": "Abcd@123" },
     { "UserID": "Abhay", "Password": "Abcd@123" },
   
];

var GenderData = [
     { "gender": "Male" },
     { "gender": "Female" },

];

var RoleData = [
     { "Role": "Architect" },
     { "Role": "Test Lead" },
     { "Role": "Manager" },
     { "Role": "Developer" },
];



var RepositoryData = [
     { "Key": "UserIDLabel", "Value": "User ID" },
     { "Key": "EmployeeNameLabel", "Value": "Employee Name" },
     { "Key": "EmpIDLabel", "Value": "Emp ID" },
     { "Key": "EmployeeNameLabel", "Value": "Employee Name" },
     { "Key": "SalaryLabel", "Value": "Salary" },
     { "Key": "DOJLabel", "Value": "DOJ" },
     { "Key": "GenderLabel", "Value": "Gender" },
     { "Key": "RoleLabel", "Value": "Role" },
     { "Key": "SearchLabel", "Value": "Search" },
     { "Key": "removeLabel", "Value": "remove" },
     { "Key": "AddLabel", "Value": "Add" },
     { "Key": "BackLabel", "Value": "Back" },
     { "Key": "EmpNameReqMessage", "Value": "Name is required!" },
     { "Key": "UserIDReqMessage", "Value": "User ID is mandatory!" },
     { "Key": "PassReqMessage", "Value": "Password is mandatory!" },
     { "Key": "UserPassNotMatchMessage", "Value": "User name and Password does not match!" },
     { "Key": "SalaryNVMessage", "Value": "Not valid Salary!" },     
];